---
# tasks file for ansible-role-maxscale
- name: Create maxscale database users
  include_tasks: db-preparation.yml

- name: Install maxscale
  include_tasks: install.yml
  when:
    - maxscale_use_docker|bool == false

- name: Start docker container
  include_tasks: docker.yml
  when:
    - maxscale_use_docker|bool == true
