---
- name: set repository via MariaDB installscript
  shell: curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash
  when: 
    - maxscale_install_repo_script|bool == true

- name: install maxscale
  yum:
    name: maxscale
    state: present

- name: create maxscale config
  template:
    src: maxscale.cnf.j2
    dest: "{{ maxscale_config_file_path }}"
    mode: 0644
  notify: verify maxscale config

- name: enable maxscale
  service:
    name: maxscale
    enabled: true
