---
- name: set repository via MariaDB installscript
  shell: curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash

- name: set repository
  yum_repository:
    name: "mariadb-maxscale"
    baseurl: "https://dlm.mariadb.com/repo/maxscale/latest/yum/rhel/7/x86_64"
    gpgcheck: true
    gpgkey: "file:///etc/pki/rpm-gpg/MariaDB-MaxScale-GPG-KEY"
    #exclude: ""
    #proxy: ""
    description: "MariaDB MaxScale"
  when:
    - (ansible_facts['ansible_os_family'] == "CentOS") OR
      (ansible_facts['ansible_os_family'] == "RedHat")
    - ansible_facts['ansible_distribution_major_version'] == "7"

- name: install maxscale
  yum:
    name: maxscale
    state: present

- name: create maxscale config
  template:
    src: maxscale.cnf.j2
    dest: "{{ maxscale_config_file_path }}"
    mode: 0644
  notify: verify maxscale config

- name: enable maxscale
  service:
    name: maxscale
    enabled: true
